# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
    { on = ['c', 'm'], run = "plugin chmod", desc = "Chmod on selected files" },
    { on = "<A-p>", run = "plugin toggle-pane min-preview", desc = "Hide or show preview" },
    { on = "M", run = "plugin toggle-pane max-preview", desc = "Maximize or restore preview" },
    # { on = "f", run = "plugin jump-to-char", desc = "Jump to char" },
    { on = "<C-y>", run = "plugin wl-clipboard", desc = "Copy wl-clipboard" },
    { on = ['g', 'D'], run = "cd ~/Downloads/", desc = "Go to Downloads" },
    { on = ['g', 'd'], run = "cd ~/Documents/", desc = "Go to Documents" },
    { on = ['g', 'c'], run = "cd ~/.config/", desc = "Go to Config" },
    { on = ['g', 'o'], run = "cd /mnt/SSD-playing\\ games/Workspace/obsidian_aio/", desc = "Go to Obsidian_aio" },
    { on = ['g', 'k'], run = "cd ~/Documents/obsidian_aio/Code model/Knowledge/", desc = "Go to Knowledge note" },
    { on = ['i', 'c'], run = "plugin ouch --args=zip", desc = "Compress with ouch" },
]
