# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing
# 
exec-once = corectrl
exec-once = otd-daemon # run driver veikk

exec-once=fcitx5-remote -r
exec-once=fcitx5 -d --replace
exec-once=fcitx5-remote -r

exec-once = warp-taskbar
# exec-once = sway 

exec-once = waybar -c ~/.config/waybar/primary_screen/config.jsonc
exec-once = waybar -c ~/.config/waybar/secondary_screen/config.jsonc
# exec-once = waybar

exec = gsettings set org.gnome.desktop.interface icon-theme 'Nordzy'
exec = gsettings set org.gnome.desktop.interface cursor-theme 'Gruvbox'

exec = hyprctl setcursor Gruvbox-Retro 20
