
# You can put your preferred keybinds here
# https://wiki.hyprland.org/Configuring/Binds/

unbind = Super, W
unbind = Super, T
unbind = Alt, E
# disbale side
unbind = Super, B
unbind = Super, M
unbind = Super, N
unbind = Super, E

# monve workspace
unbind = Super, H
unbind = Super, J
unbind = Super, K
unbind = Super, L
unbind = Ctrl+Alt, mouse_down
unbind = Ctrl+Alt, mouse_up
unbind = SUPER, mouse:273


# move focus
bind = Alt, H, exec, source /home/duckq1u/.config/hypr/scripts/focusStateToLeft.sh # [hidden]
bind = Alt, L, exec, source /home/duckq1u/.config/hypr/scripts/focusStateToRight.sh # [hidden]
bind = Alt, K, fullscreenstate, 0 # [hidden]
bind = Alt, K, movefocus, u # [hidden]
bind = Alt, J, fullscreenstate, 0 # [hidden]
bind = Alt, J, movefocus, d # [hidden]

##! Move window
bind = Ctrl+Alt, H, exec, source /home/duckq1u/.config/hypr/scripts/windowtoleft.sh # [hidden]
bind = Ctrl+Alt, L, exec, source /home/duckq1u/.config/hypr/scripts/windowtoright.sh # [hidden]
bind = Ctrl+Alt, K, movewindow, u # [hidden]
bind = Ctrl+Alt, J, movewindow, d # [hidden]

## switch workspace
bind = Shift+Alt, L, exec, source /home/duckq1u/.config/hypr/scripts/workspaceV2inscrease.sh
bind = Shift+Alt, H, exec, source /home/duckq1u/.config/hypr/scripts/workspaceV2descrease.sh
bindt = Ctrl+Alt, mouse:272, exec, source /home/duckq1u/.config/hypr/scripts/workspaceV2descrease.sh
bindt = Ctrl+Alt, mouse:273, exec, source /home/duckq1u/.config/hypr/scripts/workspaceV2inscrease.sh

bindm = ALT, mouse:272, movewindow # [hidden]

bind = Alt, Q, killactive, 
bind = Alt, F, fullscreen, 1 
bind = Shift+Alt, F, fullscreen, 0 
bind = Alt, E, exec, nautilus --new-window # Launch Nautilus (file manager)

bind = Alt, T, exec, kitty
bind = Alt, B, exec, thorium-browser --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime # phai them cai nay vao no moi chay tren wayland chuan xac duoc
bind = Shift+Alt, B, exec, brave
bind = Alt, O, exec, obsidian 
bind = Alt, V, exec, vesktop --no-sandbox --ozone-platform=wayland --ozone-platform-hint=auto --enable-features=UseOzonePlatform,WaylandWindowDecorations %U


bind = SUPER, SUPER_L, exec, pkill -x rofi || $scrPath/rofilaunch.sh d # launch application launcher
bind = Ctrl+SUPER, Ctrl+SUPER_L, exec, rofi


bind = Alt, M, exec, volumecontrol.sh -s ''


$mainMod = Super # super / meta / windows key
$scrPath = $HOME/.local/share/bin # set scripts path

bind = $mainMod+Shift, S, exec, $scrPath/screenshot.sh sf # partial screenshot capture (frozen screen)
bind = , Print, exec, $scrPath/screenshot.sh p # all monitors screenshot capture

